version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      MODE: production
  postgres:
    image: postgres:9.6.3
    ports:
      - "2345:2345"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"